-- Last updated: 6/13/2026, 12:11:49 AM
CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
    DECLARE NM INT;
    SET NM=N-1;
  RETURN (
    SELECT DISTINCT SALARY AS getNthHighestSalary FROM Employee ORDER BY SALARY DESC LIMIT 1 OFFSET NM

  );
END